# Asset Tracker Pro - Cloudflare Worker Configuration
name = "asset-tracker-pro"
main = "src/index.js"  # Or wherever your Worker entry point lives
compatibility_date = "2025-06-20"

# If you're using D1
[[d1_databases]]
binding = "DB"
database_name = "asset_tracker_db"
database_id = "YOUR-D1-DATABASE-ID"

# Optional: Environment variables
[vars]
NODE_ENV = "production"
APP_NAME = "Asset Tracker Pro"
APP_VERSION = "1.0.0"
